config/routes.rb
Smedium::Application.routes.draw do

  root :to => 'static_pages#home'

  get '/about', to: 'static_pages#about'

  get 'auth/twitter/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get '/signout', to: 'sessions#destroy', as: 'signout'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  

  resources :users, :except => :show
  get '/:profile_url/register', to: 'users#register', as: 'register'
  get '/:profile_url', to: 'users#show', as: 'profile'
  get '/me/settings', to: 'users#settings', as: 'settings'

end
  
 

app/models/user.rb
class User < ActiveRecord::Base

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :provider, presence: true
  validates :uid, presence: true, uniqueness: true
  validates :email, unless: "email.nil?", format: { with: VALID_EMAIL_REGEX }
  
  def self.from_omniauth(auth)
    where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end
  
  def self.create_from_omniauth(auth)
    before_save :create_profile_url

    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.nickname = auth["info"]["nickname"]
      user.name = auth["info"]["name"]
      user.image = auth['info']['image'].sub("_normal", "")
    end
  end

  def to_param
    profile_url
  end

  private
  
  def create_profile_url
    self.profile_url = "@" + nickname.downcase.strip.parameterize
  end

end

# (seomthing || "").function
# something.to_s.function

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = @user.id

    if @user.email.blank?
      redirect_to register_path @user
    else
      redirect_to root_url, notice: "Signed in!"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  attr_accessor :email, :image
  before_action :get_user

  def register
    @user = User.find_by_profile_url(params[:profile_url])
  end

  def settings
    if current_user.blank?
      flash[:warning] = "Please sign in to do that"
      redirect_to root_url
    else
      @user = current_user
    end
  end

  def edit
    if current_user.blank?
      flash[:warning] = "Please sign in to do that"
      redirect_to root_url
    else
      @user = current_user
    end
  end

  def update
    @user.update_attributes(params.require(:user).permit(:email))
    if @user.save
      UserMailer.email_confirm(@user).deliver
      flash[:notice] = "Settings updated"
      redirect_to root_url
    else
      flash[:notice] = "Please try again"
      render 'settings'
    end
  end

  def show
    @user = User.find_by_profile_url(params[:profile_url])
  end

private
  def get_user
    @user = User.find_by_profile_url(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

# Returns the Twitter image for the given user.
  def portrait_for(user, size)
    
    # Twitter
    # mini (24x24)                                                                  
    # normal (48x48)                                            
    # bigger (73x73)                                                
    # original (variable width x variable height)

    if user.image.include? "twimg"

      # determine filetype        
      case 
      when user.image.downcase.include?(".jpeg")
          filetype = ".jpeg"
      when user.image.downcase.include?(".jpg")
          filetype = ".jpg"
      when user.image.downcase.include?(".gif")
          filetype = ".gif"
      when user.image.downcase.include?(".png")
          filetype = ".png"
      else
          raise "Unable to read filetype of Twitter image for User ##{self.id}"
      
      end
    end

        # return requested size - code not used yet, but may be later
    #     if size == "original"
    #         return self.image
    #     else
    #         return .image.gsub(filetype, "_#{size}#{filetype}")
    #     end

    # end

    image_url = user.image.gsub(filetype, "_#{size}#{filetype}")
    image_tag(image_url, alt: user.nickname, class: "portrait_#{size}")
  end

end

app/views/layouts/_analytics.html.erb
<!-- Google Analytics -->

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= ENV['GA_PROPERTY_ID'] %>', '<%= ENV['GA_DOMAIN'] %>');
  ga('send', 'pageview');

</script>

app/views/layouts/_debug.html.erb
<debug>
	<div class="panel radius">
		<p>
			<h5><%= "params:" %></h5>
			<p><%= debug(params).to_s %></p>
			<br>
			<h5><%= "@user:" %></h5>
			<%= debug(@user) %>
			<br>
			<h5><%= "current_user:" %></h5>
			<%= debug(current_user) %>
		</p>
	</div>
</debug>

app/views/layouts/_footer.html.erb
<footer id='sticky-footer'>
  <div id='footer-contents'>
    <span class='footer-text'>
      <a href="https://github.com/rcolinkennedy/smedium/">smedium</a>
      by
      <a href="https://github.com/rcolinkennedy">rcolinkennedy</a>
    </span>
    <span>
      <ul>
        <li><%= link_to "home", root_path %></li>
        <li><%= link_to "about", about_path %></li>
      </ul>
    </span>
  </div>
</footer>

app/views/layouts/_header_image.html.erb
<div class='image-header-bleed'>
	<div style='background-image: url(<%=yield(:header_image_url) %>)' id='header-image'>
	</div>
</div>
<div class='image-overlay'>
</div>

app/views/layouts/_hero.html.erb
<header class='hero'>
	<div class='align-block'>
		<h2 class='hero-title'><%= yield(:hero_title) %></h2>
		<h4 class='hero-description'><%= yield(:tagline) %></h4>
	</div>
</header>

app/views/layouts/_left_panel.html.erb
<% if current_user %>
  <ul class='off-canvas-list'>
    <li><label>smedium </label></li>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "#{current_user.name}", profile_path(current_user) %></li>
    <li><%= link_to "Settings", '/me/settings' %></li>
    <li><%= link_to "Sign out", signout_path %></li>
    <li><%= link_to "About smedium", about_path %></li>
  </ul>       
<% else %>
  <ul class='off-canvas-list'>
    <li><label>smedium </label></li>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Sign in", '/auth/twitter' %></li>
    <li><%= link_to "About smedium", about_path %></li>
  </ul>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %> 
	<% if msg.is_a?(String) %>
		<div data-alert class="alert-box <%= name == :notice ? "info" : "alert" %>">
			<%= content_tag :div, msg %>
			<a href="#" class="close">&times;</a>
		</div>
	<% end %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" style='height: 100%'>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %> | smedium </title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= render 'layouts/analytics' if Rails.env.production? %>
  </head>

  <body style='height: 100%' onload='setTimeout(function() {window.scrollTo(0, 1)}, 100)'>
    <div class='off-canvas-wrap' style='height: 100%'>
      <div class='inner-wrap' style='height: 100%'>
        <aside class='left-off-canvas-menu'>
          <%= render 'layouts/left_panel' %>
        </aside>
          <nav class='left-off-canvas-toggle nav-button site-nav' tabindex='-1'>S</nav>
          <div class='container' id='container'>
            <div class='screen-content'>
              <div class='image-header'>
                <%= render 'layouts/header_image' %>
              </div>
              <div class='layout-foreground'>
                <%= render 'layouts/hero' %>
                
                <div id='app-content'>
                  <%= render 'layouts/messages' %>
                  <%= yield %>
                  <%= render 'layouts/debug' if Rails.env.development? %>
                </div>
              </div>
              <%= render 'layouts/footer' %>
            </div>
          </div>    
          <a class='exit-off-canvas'></a>
        </div>
      </div>
    </div>
  </body>
  <%= javascript_include_tag "application" %>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>- <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<% provide(:hero_title, "About") %>
<% provide(:tagline, "Why we're here") %>
<% provide(:header_image_url, 'http://24.media.tumblr.com/b81ed66fb77aa71f7e92da85d4ffc55e/tumblr_mopqamedKu1st5lhmo1_1280.jpg') %>

<div class='page-content'>
  <div id='smedium-info'>
    <h3 class="subheader">We were enamored.</h3>
    <p>        
      About to start a new project, my co-founder and I wanted to mimic the signup/sign in process from <a href="http://medium.com">medium.com</a>, and then we thought their layout was awesome, and then... Well, one thing led to another and now you're looking at this little project.
      <br>
      Simply put, if smedium had existed, it would have saved us a good chunk of work, so we throught we'd build this and share with friends like you.
      It's a fairly simple Rails app (Rails 4.0.1, Ruby 2.0.0) built using <a href="http://foundation.zurb.com/">Zurb's excellent Foundation 5</a> to help anyone jump start a project. It's extensible, nicely formatted, and fairly DRY. We kept it as simple as possible, by doing things like minimal User models and no javascript other than what's built into <a href="http://foundation.zurb.com/">Foundation</a>.
    </p>
    <h6 >Why smedium? It's a small version of Medium.</h6>
    <% if current_user %>
      <p>
      So give it a shot; you can <a href="https://github.com/rcolinkennedy/smedium/">check it out on GitHub</a> and be rocking and rolling after a fork and a clone.
      </p>  
    <% else %>
      <p>
      So give it a shot; <%= link_to "Sign in with Twitter", '/auth/twitter' %> to check out how it works; if you dig it, you can <a href="https://github.com/rcolinkennedy/smedium/">check it out on GitHub</a> and be rocking and rolling after a fork and a clone.
      </p>
    <% end %>
    <div class='cta-box'>
      <h6>Thanks for stopping by.</h6>
    	<%= link_to "Home", root_path, :class => "button radius" %>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<% provide(:hero_title, "smedium") %>
<div class='page-content'>
	<% if current_user %>
    <% provide(:tagline, "Welcome to the party") %>
    <% provide(:header_image_url, 'http://25.media.tumblr.com/b3d8cc24ae0595168e73d773e1c9b6b9/tumblr_mvyxuasfJ91st5lhmo1_1280.jpg') %> 
    <div>
      <h3 class='subheader'>Signed in as <%= link_to "@#{current_user.nickname}", profile_path(current_user) %></h3>
      <div id='smedium-info'>
        <p>
          This is a sample logged in homepage for
          <a href='https://github.com/rcolinkennedy/smedium/'>smedium by rcolinkennedy</a>
          <br>When you build your own web app, you can add static homepage content for your logged-in users here, or you can insert your live application.
          <br>
          When a user is logged in, the items in the <a class='left-off-canvas-toggle'>left panel menu</a> change to allow them to see their profile, settings, etc.
          <br>
          Learn more on our 
          <%= link_to "About page", about_path %>
        </p>
      </div>
    </div>
	<% else %>
    <% provide(:tagline, "An elegant starting point") %>
    <% provide(:header_image_url, 'http://24.media.tumblr.com/6cd60ec5d38560f851ad6856acc7f7ff/tumblr_myp94uOjbG1st5lhmo1_1280.jpg') %>
    <div>
      <h3 class='subheader'>Welcome home</h3>
      <div id='smedium-info'>
        <p>
          This is a sample homepage for
          <a href='https://github.com/rcolinkennedy/smedium/'>smedium by rcolinkennedy</a>, an open-source Rails app to help you jump-start your projects.
          <br> When you build your own application, your landing page content can go here.
          <br>
          Learn more on our 
          <%= link_to "About page", about_path %>
          or just <a href='https://github.com/rcolinkennedy/smedium/fork'>go ahead and fork it.</a>
        </p>
      </div>
    </div>
    <div class='cta-box'>
      <h3>Log into your account or create one with Twitter</h3>
      <%= link_to "Sign in with Twitter", '/auth/twitter', :class => 'button radius' %>
    </div>
	<% end %>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit') %>
<% provide(:hero_title, "Edit") %>
<% provide(:tagline, "Update User info") %>
<% provide(:header_image_url, 'http://25.media.tumblr.com/ce9f48e8642ecc4d1d0edda76d16b9ed/tumblr_mnh1jdFvHR1st5lhmo1_1280.jpg') %>


<div id='profile-info'>
  <div id='profile_photo'><%= portrait_for(@user,'bigger') %></div>
  <h1><%= link_to "@#{@user.nickname}", profile_path(@user) %></h1>
</div>  <div class='page-content'>
  <% if current_user %>
    <div id='smedium-info'>
      <p>
        This is a the /users/edit page that's typical in Rails; when you need to implement an admin functionality, this is where you can manage user info, since Users are made with Rails resourceful routes.
        <br>
        Since all we've done is gather the email address at this point, that's all it's used for. As you extend your application, you can use it for other settings specific to your implementation.
      </p>
    </div>
    <div class ='cta-box'>
      <h4>Update User's email address</h4>
      <p>
        <div>
          <%= form_for @user do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <%= f.text_field :email %>
          <%= f.submit "Update", :class => 'button radius' %>
          <%= link_to "Home", root_path, :class => 'button radius' %>
          <% end %>
        </div>
      </p>
    </div>
  <% else %>
    <p>
      <h3>Log into your account or create one with Twitter</h3>
      <%= link_to "Sign in with Twitter", "/auth/twitter", :class => 'button radius' %>
    </p>
  <% end %>
</div>

<!-- Found at http://localhost:3000/users/<username>/edit -->

app/views/users/register.html.erb
<% provide(:title, 'Register') %>
<% provide(:hero_title, "Register") %>
<% provide(:tagline, "One last step") %>
<% provide(:header_image_url, 'http://25.media.tumblr.com/408fbfeae2d8590512b9fc9cc6207090/tumblr_mr807bH7hh1st5lhmo1_1280.jpg') %>

<div id='profile-info'>
  <div id='profile_photo'><%= portrait_for(current_user,'bigger') %></div>
  <h1>Welcome, <%= current_user.name %></h1>
  <br>
  <h2>So nice to see you.</h2>
</div>  
<div class='cta-box'>
	<h4>Enter your email address below to finish registration.</h4>
  <div>
    <%= form_for @user do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.text_field :email %>
    <%= f.submit "Complete Registration", :class => 'button radius' %>
    <% end %>
  </div>
</div>

  <!-- Found at http://localhost:3000/<username>/register -->

app/views/users/settings.html.erb
<% provide(:title, 'Settings') %>
<% provide(:hero_title, "Settings") %>
<% provide(:tagline, "Customize your experience") %>
<% provide(:header_image_url, 'http://24.media.tumblr.com/25a89be9a2a31bd0c97fafe17761e350/tumblr_mtax0twHix1st5lhmo1_1280.jpg') %>

<div id='profile-info'>
  <div id='profile_photo'><%= portrait_for(current_user,'bigger') %></div>
  <h1><%= link_to "@#{current_user.nickname}", profile_path(current_user) %></h1>
</div>  
<div class='page-content'>
  <% if current_user %>
    <div id='smedium-info'>
      <p>
        This is a User's settings page; since all we've done is gather the email address at this point, that's all it's used for. As you extend your application, you can use it for other settings specific to your implementation.
      </p>
    </div>
    <div class ='cta-box'>
      <h4>Update your email address</h4>
      <p>
        <div>
          <%= form_for @user do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <%= f.text_field :email %>
          <%= f.submit "Update", :class => 'button radius' %>
          <%= link_to "Nevermind", root_path, :class => 'button radius' %>
          <% end %>
        </div>
      </p>
    </div>
  <% else %>
    <p>
      <h3>Log into your account or create one with Twitter</h3>
      <%= link_to "Sign in with Twitter", '/auth/twitter', :class => 'button radius' %>
    </p>
  <% end %>
</div>
  
<!-- Found at http://localhost:3000/me/settings -->

app/views/users/show.html.erb
<% provide(:title, @user.nickname ) %>
<% provide(:hero_title, '@'+@user.nickname) %>
<% provide(:tagline, "See yourself here") %>
<% provide(:header_image_url, 'http://31.media.tumblr.com/5d40ddbd07fc716e715bd5462e305edd/tumblr_mx3tmhXNNE1st5lhmo1_1280.jpg') %>

<div id='profile-info'>
  <div id='profile_photo'><%= portrait_for(@user,'bigger') %></div>
  <h1><%= @user.name %></h1>
</div>  
<div class='page-content'>
  <div id='smedium-info'>
    <p>
      This is a sample public Profile page for
      <a href="https://github.com/rcolinkennedy/smedium/">smedium by rcolinkennedy</a>
      <br>
      You can see a User's Twitter profile image here, which we are pulling in using <a href='https://github.com/intridea/omniauth'>OmniAuth</a>, and there are styles throughout the applicaction to reference it in three sizes, two of them smaller than the one above, for use in feeds and such.
      <br>
      We didn't pull profile info from Twitter, but it's easy to set up as a new object for the user and pull it in, and you can present it here. For other projects, you can put stats about a user and more in this panel. 
    </p>
  </div>
</div>